server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://${MYSQL_URL}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: bumaview
jwt:
  secret-key: ${JWT_SECRET_KEY}